rename table achivements_achivementgroup to achievements_achievementgroup;
rename table achivements_achivement to achievements_achievement;
rename table achivements_award to achievements_award;
rename table achivements_privacy to achievements_privacy;
rename table achivements_eventattendanceachivement to achievements_eventattendanceachievement;
rename table achivements_groupmembersachivement to achievements_groupmembersachievement;

ALTER TABLE achievements_privacy change public_achivements public_achievements tinyint(1) not null default 0;
ALTER TABLE achievements_award change achivement_id achievement_id varchar(50) not null;
ALTER TABLE achievements_eventattendanceachievement change achivement_id achievement_id varchar(50) not null;
ALTER TABLE achievements_groupmembersachievement change achivement_id achievement_id varchar(50) not null;

ALTER TABLE achievements_achievement                                     ENGINE = innodb;
ALTER TABLE achievements_achievementgroup                                ENGINE = innodb;
ALTER TABLE achievements_award                                           ENGINE = innodb;
ALTER TABLE achievements_privacy                                         ENGINE = innodb;
ALTER TABLE achievements_eventattendanceachievement                      ENGINE = innodb;
ALTER TABLE achievements_groupmembersachievement                         ENGINE = innodb;
ALTER TABLE auth_group                                                   ENGINE = innodb;
ALTER TABLE auth_group_permissions                                       ENGINE = innodb;
ALTER TABLE auth_message                                                 ENGINE = innodb;
ALTER TABLE auth_permission                                              ENGINE = innodb;
ALTER TABLE auth_user                                                    ENGINE = innodb;
ALTER TABLE auth_user_groups                                             ENGINE = innodb;
ALTER TABLE auth_user_user_permissions                                   ENGINE = innodb;
ALTER TABLE booking_cinema                                               ENGINE = innodb;
ALTER TABLE booking_reservation                                          ENGINE = innodb;
ALTER TABLE comicparty_order                                             ENGINE = innodb;
ALTER TABLE concrete5_groupsmapper                                       ENGINE = innodb;
ALTER TABLE country                                                      ENGINE = innodb;
ALTER TABLE django_admin_log                                             ENGINE = innodb;
ALTER TABLE django_content_type                                          ENGINE = innodb;
ALTER TABLE django_session                                               ENGINE = innodb;
ALTER TABLE django_site                                                  ENGINE = innodb;
ALTER TABLE eventmode_eventmode                                          ENGINE = innodb;
ALTER TABLE eventmode_eventmodemachine                                   ENGINE = innodb;
ALTER TABLE eventmode_note                                               ENGINE = innodb;
ALTER TABLE events_attend                                                ENGINE = innodb;
ALTER TABLE events_attendstatechange                                     ENGINE = innodb;
ALTER TABLE events_event                                                 ENGINE = innodb;
ALTER TABLE events_option                                                ENGINE = innodb;
ALTER TABLE events_optiongroup                                           ENGINE = innodb;
ALTER TABLE events_selection                                             ENGINE = innodb;
ALTER TABLE events_suboption                                             ENGINE = innodb;
ALTER TABLE htdigest_compatiblepassword                                  ENGINE = innodb;
ALTER TABLE htdigest_htdigestfile                                        ENGINE = innodb;
ALTER TABLE htdigest_htdigestfile_groups                                 ENGINE = innodb;
ALTER TABLE invoice_invoice                                              ENGINE = innodb;
ALTER TABLE invoice_invoicepaymentworkflow                               ENGINE = innodb;
ALTER TABLE invoice_invoicerevision                                      ENGINE = innodb;
ALTER TABLE invoice_line                                                 ENGINE = innodb;
ALTER TABLE invoice_payment                                              ENGINE = innodb;
ALTER TABLE kitamembership_membership                                    ENGINE = innodb;
ALTER TABLE kitamembership_yearlyrate                                    ENGINE = innodb;
ALTER TABLE logger_entry                                                 ENGINE = innodb;
ALTER TABLE logger_savedlog                                              ENGINE = innodb;
ALTER TABLE mailcenter_attendconditions                                  ENGINE = innodb;
ALTER TABLE mailcenter_attendconditions_attends_selection_argument       ENGINE = innodb;
ALTER TABLE mailcenter_boundattendconditions                             ENGINE = innodb;
ALTER TABLE mailcenter_boundattendconditions_attends_selection_argument  ENGINE = innodb;
ALTER TABLE mailcenter_emailspecification                                ENGINE = innodb;
ALTER TABLE mailcenter_emailspecification_recipients                     ENGINE = innodb;
ALTER TABLE mailcenter_mail_recipients                                   ENGINE = innodb;
ALTER TABLE mailcenter_userconditions                                    ENGINE = innodb;
ALTER TABLE mailer_dontsendentry                                         ENGINE = innodb;
ALTER TABLE mailer_message                                               ENGINE = innodb;
ALTER TABLE mailer_messagelog                                            ENGINE = innodb;
ALTER TABLE members_emailchangerequest                                   ENGINE = innodb;
ALTER TABLE members_usercommunication                                    ENGINE = innodb;
ALTER TABLE members_userlocation                                         ENGINE = innodb;
ALTER TABLE members_userprofile                                          ENGINE = innodb;
ALTER TABLE members_userwebsite                                          ENGINE = innodb;
ALTER TABLE profile_userprivacy                                          ENGINE = innodb;
ALTER TABLE proftpd_compatiblepassword                                   ENGINE = innodb;
ALTER TABLE proftpd_groupproftpdgroup                                    ENGINE = innodb;
ALTER TABLE proftpd_groupsmapper                                         ENGINE = innodb;
ALTER TABLE registration_registrationprofile                             ENGINE = innodb;
ALTER TABLE south_migrationhistory                                       ENGINE = innodb;
ALTER TABLE sso_service                                                  ENGINE = innodb;
ALTER TABLE sso_service_visible_groups                                   ENGINE = innodb;
ALTER TABLE translation_translation                                      ENGINE = innodb;
ALTER TABLE usstate                                                      ENGINE = innodb;

ALTER TABLE GroupC5Group                                                convert to character set utf8;
ALTER TABLE achievements_achievement                                    convert to character set utf8;
ALTER TABLE achievements_achievementgroup                               convert to character set utf8;
ALTER TABLE achievements_award                                          convert to character set utf8;
ALTER TABLE achievements_privacy                                        convert to character set utf8;
ALTER TABLE achievements_eventattendanceachievement                     convert to character set utf8;
ALTER TABLE achievements_groupmembersachievement                        convert to character set utf8;
ALTER TABLE auth_group                                                  convert to character set utf8;
ALTER TABLE auth_group_permissions                                      convert to character set utf8;
ALTER TABLE auth_message                                                convert to character set utf8;
ALTER TABLE auth_permission                                             convert to character set utf8;
ALTER TABLE auth_user                                                   convert to character set utf8;
ALTER TABLE auth_user_groups                                            convert to character set utf8;
ALTER TABLE auth_user_user_permissions                                  convert to character set utf8;
ALTER TABLE booking_cinema                                              convert to character set utf8;
ALTER TABLE booking_reservation                                         convert to character set utf8;
ALTER TABLE comicparty_order                                            convert to character set utf8;
ALTER TABLE concrete5_groupsmapper                                      convert to character set utf8;
ALTER TABLE country                                                     convert to character set utf8;
ALTER TABLE django_admin_log                                            convert to character set utf8;
ALTER TABLE django_content_type                                         convert to character set utf8;
ALTER TABLE django_session                                              convert to character set utf8;
ALTER TABLE django_site                                                 convert to character set utf8;
ALTER TABLE eventmode_eventmode                                         convert to character set utf8;
ALTER TABLE eventmode_eventmodemachine                                  convert to character set utf8;
ALTER TABLE eventmode_note                                              convert to character set utf8;
ALTER TABLE events_attend                                               convert to character set utf8;
ALTER TABLE events_attendstatechange                                    convert to character set utf8;
ALTER TABLE events_event                                                convert to character set utf8;
ALTER TABLE events_option                                               convert to character set utf8;
ALTER TABLE events_optiongroup                                          convert to character set utf8;
ALTER TABLE events_selection                                            convert to character set utf8;
ALTER TABLE events_suboption                                            convert to character set utf8;
ALTER TABLE htdigest_compatiblepassword                                 convert to character set utf8;
ALTER TABLE htdigest_htdigestfile                                       convert to character set utf8;
ALTER TABLE htdigest_htdigestfile_groups                                convert to character set utf8;
ALTER TABLE invoice_invoice                                             convert to character set utf8;
ALTER TABLE invoice_invoicepaymentworkflow                              convert to character set utf8;
ALTER TABLE invoice_invoicerevision                                     convert to character set utf8;
ALTER TABLE invoice_line                                                convert to character set utf8;
ALTER TABLE invoice_payment                                             convert to character set utf8;
ALTER TABLE kitamembership_membership                                   convert to character set utf8;
ALTER TABLE kitamembership_yearlyrate                                   convert to character set utf8;
ALTER TABLE logger_entry                                                convert to character set utf8;
ALTER TABLE logger_savedlog                                             convert to character set utf8;
ALTER TABLE mailcenter_attendconditions                                 convert to character set utf8;
ALTER TABLE mailcenter_attendconditions_attends_selection_argument      convert to character set utf8;
ALTER TABLE mailcenter_boundattendconditions                            convert to character set utf8;
ALTER TABLE mailcenter_boundattendconditions_attends_selection_argument convert to character set utf8;
ALTER TABLE mailcenter_emailspecification                               convert to character set utf8;
ALTER TABLE mailcenter_emailspecification_recipients                    convert to character set utf8;
ALTER TABLE mailcenter_mail_recipients                                  convert to character set utf8;
ALTER TABLE mailcenter_userconditions                                   convert to character set utf8;
ALTER TABLE mailer_dontsendentry                                        convert to character set utf8;
ALTER TABLE mailer_message                                              convert to character set utf8;
ALTER TABLE mailer_messagelog                                           convert to character set utf8;
ALTER TABLE members_emailchangerequest                                  convert to character set utf8;
ALTER TABLE members_usercommunication                                   convert to character set utf8;
ALTER TABLE members_userlocation                                        convert to character set utf8;
ALTER TABLE members_userprofile                                         convert to character set utf8;
ALTER TABLE members_userwebsite                                         convert to character set utf8;
ALTER TABLE profile_userprivacy                                         convert to character set utf8;
ALTER TABLE proftpd_compatiblepassword                                  convert to character set utf8;
ALTER TABLE proftpd_groupproftpdgroup                                   convert to character set utf8;
ALTER TABLE proftpd_groupsmapper                                        convert to character set utf8;
ALTER TABLE registration_registrationprofile                            convert to character set utf8;
ALTER TABLE south_migrationhistory                                      convert to character set utf8;
ALTER TABLE sso_service                                                 convert to character set utf8;
ALTER TABLE sso_service_visible_groups                                  convert to character set utf8;
ALTER TABLE translation_translation                                     convert to character set utf8;
ALTER TABLE usstate                                                     convert to character set utf8;

ALTER DATABASE kita_selv2 CHARACTER SET utf8 COLLATE utf8_general_ci;